# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='psp_submerchant_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='PSP submerchant id'),
        ),
    ]
